#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L "Welcome to Android `getprop ro.build.version.release` / CyanogenMod-`getprop ro.cm.version`";

# Ascii Art credits: http://www.network-science.de/ascii/
# Font: rectangles   Reflection: no   Adjustment: left   Stretch: yes      Width: 80	 Text: CodyROM
$L " _____       _     _____ _____ _____ ";
$L "|     |___ _| |_ _| __  |     |     |";
$L "|   --| . | . | | |    -|  |  | | | |";
$L "|_____|___|___|_  |__|__|_____|_|_|_|";
$L "              |___|                  ";
